export const GET_PURCHASES = 'GET_PURCHASES'
export const GET_PURCHASES_SUCCESS = 'GET_PURCHASES_SUCCESS'
export const GET_PURCHASES_FAILED = 'GET_PURCHASES_FAILED'

export const REMOVE_PURCHASE = 'REMOVE_PURCHASE'
export const REMOVE_PURCHASE_SUCCESS = 'REMOVE_PURCHASE_SUCCESS'
export const REMOVE_PURCHASE_FAILED = 'REMOVE_PURCHASE_FAILED'